language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: install
      script: yarn
    - stage: lint
      script: yarn lint
    - stage: deploy
      script: npx semantic-release
env:
  - CI=true